"use client";

import Image from "next/image";
import { useRef, useState } from "react";
import { LoaderCircle, Upload } from "lucide-react";

export function LogoUploadField({ initialUrl, demoMode }: { initialUrl?: string | null; demoMode: boolean }) {
  const inputRef = useRef<HTMLInputElement>(null); const [url, setUrl] = useState(initialUrl ?? ""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const upload = async (file?: File) => { if (!file) return; if (![/image\/jpeg/, /image\/png/, /image\/webp/].some((type) => type.test(file.type)) || file.size > 5 * 1024 * 1024) { setMessage("Use PNG, JPEG ou WebP com até 5 MB."); return; } if (demoMode) { setUrl(URL.createObjectURL(file)); setMessage("Prévia local. O arquivo não será persistido no modo demo."); return; } setLoading(true); const body = new FormData(); body.set("logo", file); const response = await fetch("/api/admin/brand-logo", { method: "POST", body }); const payload = await response.json(); setLoading(false); if (response.ok) { setUrl(payload.url); setMessage("Logo enviada e ativada."); } else setMessage(payload.error ?? "Falha no envio."); };
  return <div><input type="hidden" name="logoUrl" value={url} /><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="relative grid h-32 w-48 shrink-0 place-items-center border fine-rule bg-white p-4">{url ? <Image src={url} alt="Prévia da logo" fill unoptimized className="object-contain p-3" /> : <span className="text-xs text-[var(--muted)]">Logo temporária ativa</span>}</div><div><input ref={inputRef} className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => upload(e.target.files?.[0])} /><button type="button" className="button-secondary" disabled={loading} onClick={() => inputRef.current?.click()}>{loading ? <LoaderCircle className="animate-spin" size={15} /> : <Upload size={15} />}{loading ? "Enviando..." : "Enviar logo"}</button>{url && <button type="button" className="ml-3 min-h-11 text-xs font-semibold underline" onClick={() => setUrl("")}>Usar logo temporária</button>}<p className="mt-2 max-w-md text-xs leading-relaxed text-[var(--muted)]">PNG, JPEG ou WebP. SVG enviado por usuário não é aceito.</p>{message && <p role="status" className="mt-2 text-xs text-[var(--accent)]">{message}</p>}</div></div></div>;
}
