import { LogOut, MessageCircle } from "lucide-react";
import { sellerLogoutAction } from "@/app/vendedor/actions";
import { requireSeller } from "@/lib/auth";
import { getCatalogSettings } from "@/lib/catalog";
import { formatDateTime, formatPrice } from "@/lib/format";
import { mapOrder, orderSelect } from "@/lib/orders";
import { paymentLabel } from "@/lib/order-status";
import { resolveSiteUrl } from "@/lib/site-url";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { buildWhatsAppUrl, renderWhatsAppTemplate } from "@/lib/whatsapp";
import { CouponLink } from "@/components/admin/operations-forms";

export const dynamic="force-dynamic";
export const metadata={title:"Meus pedidos — Vendedor"};
export default async function SellerPage(){const[{profile},settings]=await Promise.all([requireSeller(),getCatalogSettings()]);const supabase=await createSupabaseServerClient();const[{data:rows},{data:coupons}]=await Promise.all([supabase.from("orders").select(orderSelect).order("created_at",{ascending:false}),supabase.from("coupons").select("code,source_name").eq("active",true)]);const orders=(rows??[]).map(row=>mapOrder(row));const baseUrl=resolveSiteUrl().origin;return <main id="conteudo" className="min-h-screen bg-[#efede7] p-4 sm:p-8"><header className="mx-auto flex max-w-6xl items-center justify-between border-b fine-rule pb-5"><div><p className="eyebrow text-[var(--muted)]">Painel do vendedor</p><h1 className="mt-2 text-3xl font-medium">Olá, {profile.name}</h1></div><form action={sellerLogoutAction}><button className="button-secondary"><LogOut size={15}/>Sair</button></form></header><div className="mx-auto max-w-6xl"><section className="py-7"><h2 className="eyebrow mb-3">Seus links</h2>{(coupons??[]).length?(coupons??[]).map(c=><div key={c.code} className="mb-3 grid gap-1 sm:grid-cols-[12rem_1fr] sm:items-center"><strong className="text-sm">{c.source_name}</strong><CouponLink code={c.code} baseUrl={baseUrl}/></div>):<p className="text-sm text-[var(--muted)]">O admin ainda não vinculou um cupom a você.</p>}</section><section className="border-t fine-rule"><h2 className="eyebrow py-5">Pedidos atribuídos</h2>{orders.length?orders.map(order=>{const message=renderWhatsAppTemplate(settings.orderWhatsappTemplate,{nome:order.customerName,vendedora:profile.name,numero:order.id.slice(0,8).toUpperCase(),produto:order.productName,total:formatPrice(order.totalAmount),status:paymentLabel(order.paymentStatus),cupom:order.couponCode??""});const url=buildWhatsAppUrl(order.customerPhone,message);return <article key={order.id} className="grid gap-3 border-t fine-rule py-5 sm:grid-cols-[8rem_1fr_9rem_8rem_3rem] sm:items-center"><span className="text-xs text-[var(--muted)]">{formatDateTime(order.createdAt)}</span><span><strong className="block">{order.customerName}</strong><small>{order.productName} · {order.couponCode}</small></span><span>{paymentLabel(order.paymentStatus)}</span><strong>{formatPrice(order.totalAmount)}</strong>{url?<a href={url} target="_blank" rel="noreferrer" className="grid size-11 place-items-center border fine-rule" aria-label={`Falar com ${order.customerName}`}><MessageCircle size={17}/></a>:<span/>}</article>}):<p className="border-t fine-rule py-8 text-sm text-[var(--muted)]">Nenhum pedido atribuído.</p>}</section></div></main>}
